### ISSUE TITLE
Not available yet on Sacana Wrapper?

### ISSUE THREAD

**Issue by 0xh3LL0** [marcussacana/EscudeEditor#1]
![not available](https://user-images.githubusercontent.com/23132217/39793229-c078b240-536e-11e8-893f-b0d18c1f8806.JPG)

**Comment by marcussacana** [comment]
Yes, I'll add it now...
Strange as it may seem, I simply forgot to publish the plugin
Well, don't be scared to remind me if it happens again too...

**Comment by marcussacana** [comment]
Added, thx.

**Comment by marcussacana** [comment]
Ahh, a warning ...
I'm starting to feel the need to abandon .NET 4.0, if I do this the next tools will not work on windows xp, so consider upgrading the system.

**Comment by 0xh3LL0** [comment]
thanks!

no worries, i have win 10, i dunno which version of net will you use but i heard that net 4.7 is buggy...

**Comment by marcussacana** [comment]
4.5 but isn't sure yet...
