### ISSUE TITLE
BUG: hiragana messed up with katakana

### ISSUE THREAD

**Issue by 0xh3LL0** [marcussacana/EscudeEditor#2]
your tools seem read the hiragana as katakana, kanji is readable correctly though...
<a href="https://imgur.com/YzuGWpt"><img src="https://i.imgur.com/YzuGWpt.png" title="source: imgur.com" /></a>

here is the sample script 
[script.zip](https://github.com/marcussacana/EscudeEditor/files/1990002/script.zip)

**Comment by marcussacana** [comment]
Sure... since I really don't know japanese i not noticed this...
Strange... the game uses custom encoding.... or another encryption?.... 
I will need take a proper look into this...

**Comment by marcussacana** [comment]
Well... since you know jap you know if hiragana and katakana have a "order"? 
like our alphabet have "abcdefgh"...
if have one write to me, maybe will help

**Comment by 0xh3LL0** [comment]
this is the half-katakana letter order:
> !?｡｢｣､･ｦｧｨｩｪｫｬｭｮｯｰｱｲｳｴｵｶｷｸｹｺｻｼｽｾｿﾀﾁﾂﾃﾄﾅﾆﾇﾈﾉﾊﾋﾌﾍﾎﾏﾐﾑﾒﾓﾔﾕﾖﾗﾘﾙﾚﾛﾜﾝﾞﾟ

and it should be readable as this:
> ！？　。「」、…をぁぃぅぇぉゃゅょっーあいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもやゆよらりるれろわん゛゜

that one taken from regomne's code, it used for the same engine btw:
https://github.com/regomne/chinesize/blob/master/ACPX/extBin.py#L6-L7

**Comment by marcussacana** [comment]
Thank you, try now.

**Comment by 0xh3LL0** [comment]
ok so i tried just now, but as far as i can see only the letter with dakuten (2 dot) 「**゛**」 and handakuten (small circle) 「**゜**」 are readable correctly
here is the example: 
｢ﾔｯ**ぱ**ﾘﾈ･･｡ ｿｳ**だ**ﾄﾊ思ｯﾃﾀｹ**ど**｣
the **ぱ** are **は** + **゜** and   **ど** are **と** + **゛**, the **だ** also correct
but the other letter still the same...

**Comment by marcussacana** [comment]
Now this shit will works

**Comment by marcussacana** [comment]
Welll just don't edit the script, actually you can only read the script...

**Comment by marcussacana** [comment]
Fixed, you can save the script now too...

**Comment by 0xh3LL0** [comment]
yes! thats how it should be!
thank you very much!

<a href="https://imgur.com/zMLH8RD"><img src="https://i.imgur.com/zMLH8RD.png" title="source: imgur.com" /></a>

**Comment by 0xh3LL0** [comment]
this is an off topic, but actually you dont have to pack it back to make the game read the script, i just put the script under "script" directory, and it works...
same goes to the image too, for example we just want to edit the menu but menu comes with backgrounds, and other images as well and it would be pain to pack hundreds megabyte or even gigabyte patch for this,
use it with molebox is pretty perfect!
