### ISSUE TITLE
how to translate into simplified Chinese

### ISSUE THREAD

**Issue by onecatcute** [marcussacana/EscudeEditor#3]
hello. I'm glad to your code helped me. But I have a question. I want to translate the text into simplified Chinese, but some characters are not in the Japanese database, so those characters will be changed to "?" . Can you help me out? Looking forward to your reply.

**Comment by marcussacana** [comment]
There are only 2 ways that I know, or patching the game engine, or modding a japanese font to display chinese characters instead.
Unfortally I'm not familliar with chinese to give proper instructions of what can be done.

**Comment by onecatcute** [comment]
I see. Thank you for your reply. I'll get help from someone who knows. Thank you for your direction.

**Comment by onecatcute** [comment]
How to extract game text from script//xx.bin into xx.txt and then import Modified game text from xx.txt to script//xx.bin?
Many thanks for your kind and warm reply.
your escudeeditor is very useful.but it is cumbersome for me to open script//xx.bin ，modify game's text and save them by gui.
I want to extract game text from script//xx.bin into xx.txt , and  the encode of txt is utf16 , so that i can edit it by simplified Chinese.then import Modified game text from xx.txt to script//xx.bin.
i  want to change the code, but without adept experience.
how to change the code? hope to get your help if you have free time.I'm sorry to bother you.Looking forward to your reply.

**Comment by marcussacana** [comment]
https://github.com/marcussacana/SacanaWrapper

**Comment by onecatcute** [comment]
thanks a lot for your tools,it is user-friendly and save my time.well , i have a problem in patching the game engine.i am shame-making that seek advice from you.
when i patch the game engine,i must modify the source code(file:\panicon.bin~\global.c).i meet a error that the program cannot run, like the next photo:
<img width="479" alt="image" src="https://user-images.githubusercontent.com/104288921/181038821-11cf24d8-917e-4343-8011-c18ffd0a210b.png">
it says that "global.c(1946):Describe the string in one line." . so i find the place where it say ：
<img width="544" alt="image" src="https://user-images.githubusercontent.com/104288921/181040037-19719145-df5d-44be-b853-20da93066b69.png">
i delete the "ｰ" between "ｯ" and "ｱ" and the program can run.
but it still cannot recognize simplified Chinese correctly.for example：
<img width="388" alt="02-中文" src="https://user-images.githubusercontent.com/104288921/181043912-bed3c4b0-ed88-4103-9860-09157ddd3cbe.png">
the game text  is "高原站？嗯，没错了",The first three words “高原站” are double byte,but read by single byte.and those six error character is from global.c(1945) and global.c(1946) which read by ansic encode.
<img width="532" alt="屏幕截图 2022-07-26 221821" src="https://user-images.githubusercontent.com/104288921/181045698-512527aa-de66-4266-afa0-ef34b2790fd3.png">
i think global.c is the point.i don't know much about principles so that i cannot modify source code correctly.i cantnot find related data in Internet, only ask help for you if you know.
wish you good health and good luck.
game:パニカル・コンフュージョン

**Comment by onecatcute** [comment]
Thank you very much. It seems that I can't finish Chinese localization. I'd better modify the text so that I can understand it.
