### ISSUE TITLE
Is there any convenient way to modify those data type files that cannot be unpacked?

### ISSUE THREAD

**Issue by onecatcute** [marcussacana/EscudeEditor#5]
Thank you for always making good tools.
Unpacking "game_name.bin" or "data.bin" can obtain files such as db_game.bin. There are some game texts in db_game.bin, which I can only open with the hex editor and modify line by line. It's a waste of time. Is there any way to modify it quickly?
I will appreciate your help and look forward to your reply.
The best regards!

**Comment by marcussacana** [comment]
this tool is outdated, I didn't worked with this engine for a long time therefore I don't remember details like that.
