### ISSUE TITLE
Export and injection of text files

### ISSUE THREAD

**Issue by pxBang** [marcussacana/EscudeEditor#6]
Currently, editing and modification can only be done in the GUI interface.

If you can export text files to common text formats such as ".txt" and ".xls", and package the ".txt" or ".xls" files back into a ".bin" file. This greatly expands the versatility of the software and can effectively use other text editing tools for automated modifications, greatly improving efficiency.

Looking forward to your reply！

**Comment by marcussacana** [comment]
This tool is an example and should not be used in production.
This one in particulary is pretty incomplete so, even more.

**Comment by pxBang** [comment]
Well, I just want to do personal translation text work, not for commercial use, thank you for your reply

**Comment by marcussacana** [comment]
I know, is just that this tool can't be called of stable, if you want anyway you can look at my SacanaWrapper repo.

**Comment by pxBang** [comment]
OK, I'll go take a look
